/**
 * Main entry point for the RCloud bundle.
 *
 * This file serves as the ES module entry point that replaces the Grunt-based
 * concatenation of rcloud_bundle.js. It imports all core RCloud modules in the
 * correct dependency order.
 *
 * During the build, the Vite plugin concatenates the individual source files
 * (listed in vite.config.js) to produce rcloud_bundle.js, preserving the same
 * output as the previous Grunt build. This entry point documents the module
 * structure and will serve as the foundation for future ES module migration.
 *
 * Bundle: rcloud_bundle.js
 * Modules: 83 files covering RCloud core, notebook MVC, UI components, and tree
 */

// Core RCloud API and utilities
// - htdocs/js/rcloud.js
// - htdocs/js/rclient.js
// - htdocs/js/url_utils.js
// - htdocs/js/ui_utils.js
// - htdocs/js/utils.js
// - htdocs/js/extension.js
// - htdocs/js/bootstrap_utils.js

// Notebook MVC components
// - htdocs/js/notebook/_notebook_begin.js
// - htdocs/js/notebook/_buffer_begin.js
// - htdocs/js/notebook/_cell_begin.js
// - htdocs/js/notebook/_asset_begin.js
// - htdocs/js/notebook/buffer_model.js
// - htdocs/js/notebook/asset_view.js
// - htdocs/js/notebook/asset_model.js
// - htdocs/js/notebook/asset_controller.js
// - htdocs/js/notebook/cell_view.js
// - htdocs/js/notebook/cell_model.js
// - htdocs/js/notebook/cell_controller.js
// - htdocs/js/notebook/cell_processors.js
// - htdocs/js/notebook/notebook_view.js
// - htdocs/js/notebook/notebook_model.js
// - htdocs/js/notebook/notebook_controller.js
// - htdocs/js/notebook/util.js

// Discovery, session, and language support
// - htdocs/js/discovery_model.js
// - htdocs/js/notebook.js
// - htdocs/js/session.js
// - htdocs/js/language.js
// - htdocs/js/upload_utils.js

// UI components
// - htdocs/js/ui/_begin.js
// - htdocs/js/event.js
// - htdocs/js/ui/advanced_menu.js
// - htdocs/js/ui/cell_commands.js
// - htdocs/js/ui/column.js
// - htdocs/js/ui/column_sizer.js
// - htdocs/js/ui/command_prompt.js
// - htdocs/js/ui/comments_frame.js
// - htdocs/js/ui/configure_readonly.js
// - htdocs/js/ui/fatal_dialog.js
// - htdocs/js/ui/find_replace.js
// - htdocs/js/ui/shortcut_manager.js
// - htdocs/js/ui/shortcut_dialog.js
// - htdocs/js/ui/ace_shortcuts.js
// - htdocs/js/ui/help_frame.js
// - htdocs/js/ui/image_manager.js
// - htdocs/js/ui/import_export.js
// - htdocs/js/ui/pull_and_replace.js
// - htdocs/js/ui/init.js
// - htdocs/js/ui/left_panel.js
// - htdocs/js/ui/load_options.js
// - htdocs/js/ui/menus.js
// - htdocs/js/ui/message_dialog.js
// - htdocs/js/ui/middle_column.js
// - htdocs/js/ui/navbar.js
// - htdocs/js/ui/notebook_commands.js
// - htdocs/js/ui/selection_bar.js
// - htdocs/js/ui/notebook_title.js
// - htdocs/js/ui/notebooks_frame.js
// - htdocs/js/ui/output_context.js
// - htdocs/js/ui/panel_loader.js
// - htdocs/js/ui/progress.js
// - htdocs/js/ui/prompt_history.js
// - htdocs/js/ui/right_panel.js
// - htdocs/js/ui/processing_queue.js
// - htdocs/js/ui/run_button.js
// - htdocs/js/ui/stop_button.js
// - htdocs/js/ui/scratchpad.js
// - htdocs/js/ui/search.js
// - htdocs/js/ui/session_pane.js
// - htdocs/js/ui/settings_frame.js
// - htdocs/js/ui/share_button.js
// - htdocs/js/ui/upload.js
// - htdocs/js/ui/upload_frame.js
// - htdocs/js/ui/thumb_dialog.js
// - htdocs/js/ui/notebook_protection_logger.js
// - htdocs/js/ui/notebook_protection.js
// - htdocs/js/ui/discovery_page.js

// Tree components
// - htdocs/js/tree/notebook_tree_search_service.js
// - htdocs/js/ui/incremental_search.js
// - htdocs/js/tree/date_filter.js
// - htdocs/js/tree/notebook_tree_model.js
// - htdocs/js/tree/notebook_tree_view.js
// - htdocs/js/tree/notebook_tree_controller.js

// This file is used as a Vite entry point placeholder.
// The actual bundle is generated by the rcloud-build plugin in vite.config.js.
export default {};
